spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam1?serverTimezone=GMT%2b8
    username: user
    password: 123456
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
server:
  port: 8086

exam:
  path: D:\AAA\img\

file:
  upload-path: D:\AAA\abc123

Access-Control-Allow-Origin: /
Access-Control-Allow-Credentials: true

